require("source-map-support/register"),module.exports=function(e){var t={},r={2:0};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.e=function(t){if(0!==r[t]){var n=require("./"+({0:"About",1:"Home"}[t]||t)+".js"),o=n.modules,a=n.ids;for(var c in o)e[c]=o[c];for(var i=0;i<a.length;i++)r[a[i]]=0}return Promise.all([])},n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,function(t){return e[t]}.bind(null,o));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="/",n.oe=function(e){process.nextTick(function(){throw e})},n(n.s=12)}([function(e,t){e.exports=require("react")},function(e,t){e.exports=require("path")},function(e,t){e.exports=require("react-router")},function(e,t){e.exports=require("styled-components")},function(e,t){e.exports=require("fs")},function(e,t){e.exports=require("express")},function(e,t){e.exports=require("@loadable/server")},function(e,t){e.exports=require("@loadable/component")},function(e,t,r){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.getFooter=t.getHeader=t.createScriptTag=void 0;o(r(4)),o(r(1));var n=r(15);function o(e){return e&&e.__esModule?e:{default:e}}t.createScriptTag=(({src:e})=>`<script defer="defer" src="${e}"><\/script>`);t.getHeader=(({nonce:e})=>n.html`
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="user-scalable=no,initial-scale=1.0001,maximum-scale=1.0001,viewport-fit=cover">
        </head>
        <body>
          <noscript>
            You need to enable JavaScript to run this app.
          </noscript>
          <div id="root">`);t.getFooter=(({extractor:e,nonce:t})=>{const r=`<script nonce="${t}">`,o=e.getScriptTags().replace("<script>",r);return n.html`</div>
      ${o}
    </body>
    </html>
  `})},function(e,t,r){"use strict";(function(e){var n=r(0),o=r.n(n),a=r(1),c=r.n(a),i=r(10),u=r(2),s=r(3),l=r(6),d=r(11),f=r(8);r(14)("renderer");const p=c.a.resolve(e,"../build/loadable-stats.json");t.a=((e,t)=>{const r=new l.ChunkExtractor({statsFile:p}),n=new s.ServerStyleSheet,a=n.collectStyles(o.a.createElement(l.ChunkExtractorManager,{extractor:r},o.a.createElement(u.StaticRouter,{location:e.url,context:{}},o.a.createElement(d.a,null))));t.status(200),t.setHeader("Cache-Control","s-maxage=0"),t.write(Object(f.getHeader)({nonce:""}));const c=n.interleaveWithNodeStream(Object(i.renderToNodeStream)(a));c.pipe(t,{end:!1}),c.on("end",()=>t.end(Object(f.getFooter)({extractor:r,nonce:""})))})}).call(this,"server")},function(e,t){e.exports=require("react-dom/server")},function(e,t,r){"use strict";var n=r(0),o=r.n(n),a=r(2),c=r(3),i=r.n(c),u=r(7),s=r.n(u);const l=s()(()=>r.e(1).then(r.bind(null,16)),{fallback:o.a.createElement("div",null,"loading...")}),d=s()(()=>r.e(0).then(r.bind(null,17)),{fallback:o.a.createElement("div",null,"loading...")}),f=i.a.div`
  display: flex;
  width: 100vw;
  height: 100vh;
  max-height: 100vh;
`;t.a=class extends o.a.Component{render(){return o.a.createElement(c.ThemeProvider,{theme:{primary:"rgb(83, 109, 254)",secondaryTextColor:"#70737d",gray90:"#323A3B",gray50:"#828A8B",gray30:"#B4B9B9",gray20:"#CFD2D3",gray10:"#EBECEC",gray5:"#F5F6F6"}},o.a.createElement(f,null,o.a.createElement(a.Switch,null,o.a.createElement(a.Route,{exact:!0,path:"/",component:l}),o.a.createElement(a.Route,{path:"/about",component:d}))))}}},function(e,t,r){e.exports=r(13)},function(e,t,r){"use strict";r.r(t),function(e){var t=r(5),n=r.n(t),o=r(4),a=r.n(o),c=r(1),i=r.n(c),u=r(9),s=function(e,t,r,n){return new(r||(r=Promise))(function(o,a){function c(e){try{u(n.next(e))}catch(e){a(e)}}function i(e){try{u(n.throw(e))}catch(e){a(e)}}function u(e){e.done?o(e.value):new r(function(t){t(e.value)}).then(c,i)}u((n=n.apply(e,t||[])).next())})};const l=process.env.PORT||3006,d=n()();let f;try{f=a.a.readdirSync(i.a.resolve(e,"..","build","static","js"))}catch(e){console.error(e)}d.use(n.a.static(i.a.resolve(e,"..","build"),{index:!1,setHeaders:(e,t)=>{}})),d.get("/static/js/:name",(t,r,n)=>{if(!t.params.name)return n();if(f.find(e=>e.startsWith(t.params.name)))return r.sendFile(i.a.resolve(e,"..","build","static","js",t.params.name));const o=t.params.name.match(/(\w+?)\..+js/i);if(!o)return n();const a=f.find(e=>e.startsWith(o[1]));if(!a)return n();r.redirect(`/static/js/${a}`)}),d.get("*",u.a),process.on("unhandledRejection",e=>s(void 0,void 0,void 0,function*(){console.log("Unhandled rejection",e)})),process.on("uncaughtException",e=>s(void 0,void 0,void 0,function*(){console.log("Uncaught exception",e)})),d.listen(l),console.log(`Server running at http://localhost:${l}`)}.call(this,"server")},function(e,t){e.exports=require("debug")},function(e,t){e.exports=require("common-tags")}]);
//# sourceMappingURL=main.map